Repository 310Team8/FinTrack, pull requests merged in 2024-10, with the labels that each got.

#83 Cashflow Forecasting Missing Link
  src/main/java/org/vaadin/application/MainLayout.java
  src/main/java/org/vaadin/application/views/NetCashflowForecastView.java
Labels: bug, frontend

#85 Implemented Invoice Manager
  src/main/java/org/vaadin/application/MainLayout.java
  src/main/java/org/vaadin/application/model/Invoice.java
  src/main/java/org/vaadin/application/repository/InvoiceRepository.java
  src/main/java/org/vaadin/application/service/ExpenseService.java
  src/main/java/org/vaadin/application/service/IncomeService.java
  src/main/java/org/vaadin/application/service/InvoiceService.java
  src/main/java/org/vaadin/application/utility/tempUtil.java
  src/main/java/org/vaadin/application/views/AssetView.java
  src/main/java/org/vaadin/application/views/InvoiceView.java
Labels: enhancement, backend, feature, frontend

#88 Clean up todos in asset service
  src/main/java/org/vaadin/application/service/AssetService.java
Labels: bug, backend, refactor
